### ISSUE TITLE
In simulateMethTruth() function, initialize 'diffInd' if (nGroups == 1)?

### ISSUE THREAD

**Issue by hdraisma** [stephaniehicks/quantroSim#1]
Dear Dr. Hicks,

Many thanks for creating and making available this package. I would like to use the quantroSim::simulateMethTruth() function with nGroups == 1, but this returns me the following error:

`Error: object 'diffInd' not found`

I tried to initialize the 'diffInd' variable as a NULL object, as in:
```
if(nGroups == 1){

  diffInd <- NULL

  methObsMat <- 1 / (1 + exp(-(results$simObs$normObs +
                     rnorm(nProbes, 0, 0.01))))
  output = list("objectType" = "simulateMethTruthObject",
    "nProbes" = nProbes, "nGroups" = nGroups,
    "trueParams" = results$trueParams, "simObs" = results$simObs,
                "methDiffInd" = diffInd, "methRange" = methObsMat)
}
```
... and this appears to work.

I would be grateful if you could let me know whether the apparent solution I described above would be correct. Also, perhaps you would want to implement this in the 'quantroSim' package code here.

Many thanks in advance,

Best wishes

**Comment by stephaniehicks** [comment]
Hi! Thanks for the comment. Yes, you are correct. Could you make a pull request and I'll incorporate it?

**Comment by stephaniehicks** [comment]
After merging the PR, will close this issue. Thanks!
