### ISSUE TITLE
Simulating beta matrix - methylation

### ISSUE THREAD

**Issue by jlevy44** [stephaniehicks/quantroSim#3]
Is there any planned support to simulate a beta value matrix instread of an MSet to accomodate different methylation analysis pipelines?

**Comment by stephaniehicks** [comment]
Hi @jlevy44 -- No current plans to simulate a beta value matrix, but it's something that could definitely be done. I'm a bit swamped at the moment, but if you wish to submit a pull request for it, I would gladly accept. Thanks!
