### ISSUE TITLE
Unable to create Mset 

### ISSUE THREAD

**Issue by SAADAT-Abu** [stephaniehicks/quantroSim#4]
I am following the vignettes but getting this error:

`
methTruth<- simulateMethTruth(3000, nGroups = 2, nMixtures = 3,
propMixtures = NULL, muMixtures = NULL, sigMixtures = NULL,
pDiff = 0.3, pUp = 0.5, verbose = TRUE)
data.sml <- sim <- simulateMeth(methTruth, meth.platform = "methArrays",
                    nSamps = 10, nMol = 10^6)
mset<- getMethylSet(data.sml)
Error in SummarizedExperiment(assays = assays, ...) : 
  unused argument (phenoData = new("AnnotatedDataFrame", varMetadata = list(c(NA, NA)), data = list(c("Sample_001", "Sample_002", "Sample_003", "Sample_004", "Sample_005", "Sample_006", "Sample_007", "Sample_008", "Sample_009", "Sample_010", "Sample_011", "Sample_012", "Sample_013", "Sample_014", "Sample_015", "Sample_016", "Sample_017", "Sample_018", "Sample_019", "Sample_020"), c("Group_001", "Group_001", "Group_001", "Group_001", "Group_001", "Group_001", "Group_001", "Group_001", "Group_001", "Group_001", 
"Group_002", "Group_002", "Group_002", "Group_002", "Group_002", "Group_002", "Group_002", "Group_002", "Group_002", "Group_002")), dimLabels = c("rowNames", "columnNames"), .__classVersion__ = new("Versions", .Data = list(c(1, 1, 0)))))
> ?getMethylSet
> class(data.sml)
[1] "list"`

I would be glad if you can help.
Thanks a lot

**Comment by stephaniehicks** [comment]
hi there! Thank you for your interest in this package. Unfortunately, I am not actively developing this package. Therefore, I cannot help at this time. I might be able to help in the future. I am sorry I couldn't be more helpful.
